services:
  db:
    image: postgres:15
    container_name: jobmatch_db
    environment:
      POSTGRES_DB: jobmatch
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    ports:
      - "5432:5432"
    volumes:
      - jobmatch_pgdata:/var/lib/postgresql/data

volumes:
  jobmatch_pgdata:
